version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    pre_build:
      commands:
        - echo skipped on `date`

    build:
      commands:
        - echo gradle Build `date`
        - java -version
        - gradle clean build

    post_build:
      commands:
        - echo Build completed on `date`


artifacts:
  files:
    - target/key-manager-grpc.jar
