micronaut:
  application:
    name: pix

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/pix
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  server:
    account: http://${SERVER_ITAU:localhost}:${PORT_SERVER_ITAU:9091}/api/v1/clientes
  ispb: 60701190

bcb:
  pix:
    keys: http://${SERVER_BCB:localhost}:${PORT_SERVER_BCB:8082}/api/v1/pix/keys