micronaut:
  application:
    name: pix

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

jpa.default.properties.hibernate.hbm2ddl.auto: update

erpItau:
  server:
    account: ${SERVER_ACCOUNT:`http://localhost:9091/api/v1/clientes`}