micronaut:
  application:
    name: pix

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  server:
    account: ${SERVER_ITAU:`http://localhost:9091/api/v1/clientes`}
  ispb: 60701190

bcb:
  pix:
    keys: ${SERVER_BCB:`http://localhost:8082/api/v1/pix/keys`}